'use strict';

// Из суммы вычтена комиссия платежной системы за перевод средств и конвертацию валюты.
window.г_мПожертвования =
[
	["2016-04-12",  100, "RUB", "Садовников Олег"      , "PayPal"                   , ""],
	["2016-04-12",   99, "RUB", "2687"                 , "Яндекс.Деньги"            , "спасибо за труд от RuNet) и добра тебе"],
	["2016-04-13",    3, "USD", "TMB"                  , "WebMoney"                 , "На пиво :) Спасибо за твою работу!"],
	["2016-04-13",  500, "RUB", ""                     , "Яндекс.Деньги из Сбербанк", ""],
	["2016-04-13",  145, "RUB", ""                     , "Яндекс.Деньги из КИВИ"    , ""],
	["2016-04-13",    9, "RUB", "2805"                 , "Яндекс.Деньги"            , ""],
	["2016-04-24",   60, "RUB", ""                     , "PayPal"                   , "от iG0Lki - на мороженое :)"],
	["2016-06-08",  294, "RUB", ""                     , "Яндекс.Деньги"            , "Чувак, на пивас. Не вздумай останавливаться)"],
	["2016-07-01",  200, "RUB", "Gritsenko Denis"      , "PayPal"                   , "Отличное расширение! Не забрасывай"],
	["2016-09-16",  200, "RUB", ""                     , "Яндекс.Деньги из Сбербанк", ""],
	["2017-01-09",  200, "RUB", ""                     , "Яндекс.Деньги из Сбербанк", ""],
	["2017-02-07",   55, "RUB", "Oleg Korotych"        , "WebMoney"                 , "Спасибо"],
	["2017-02-07",   10, "RUB", "5080"                 , "Яндекс.Деньги"            , "спасибо"],
	["2017-02-15",   86, "RUB", "Сергей Юрченко"       , "PayPal"                   , "спасибо. классное расширение. правда, не видно описание стрима, где часто FAQ и расписание стримов указывают"],
	["2017-04-05",  305, "RUB", "Omar Alomair"         , "PayPal"                   , ""],
	["2017-04-23",  0.6, "USD", "Miguel Bonaldi"       , "PayPal"                   , "SOY UN DIOS GENEROSO ALV XD"],
	["2017-05-29",  100, "RUB", "Юркин Александр"      , "PayPal"                   , "Единственный адекватный способ просматривать твич. Сяп."],
	["2017-06-02",  194, "RUB", "LittleMontana"        , "Яндекс.Деньги из Сбербанк", ""],
	["2017-06-02",  300, "RUB", "Цапков Алексей"       , "PayPal"                   , "Спасибо за отличное расширение! Использую его в опере и не работает BTTV, можно что-то с этим сделать?"],
	["2017-06-06",  500, "RUB", ""                     , "Яндекс.Деньги"            , "Спаситеееееель ))))"],
	["2017-06-08",  500, "RUB", "Цапков Алексей"       , "PayPal"                   , "Спасибо огромное ещё раз! BTTV заработал в опере Kreygasm"],
	["2017-06-10",  0.8, "BRL", "Alexsandro Schneider" , "PayPal"                   , "Very good plugin"],
	["2017-06-20",  9.1, "USD", "Amogh Bhatawdekar"    , "PayPal"                   , "Love this addon ! Only thing worked to fix my Twitch buffering !! Love Love love Love !!"],
	["2017-06-24",  100, "RUB", ""                     , "Яндекс.Деньги"            , "Отличное расширение, спасибо!"],
	["2017-06-24",  9.1, "USD", "Lucas Passos"         , "PayPal"                   , ""],
	["2017-07-04",  0.3, "USD", "Aleksag"              , "WebMoney"                 , "spasibo"],
	["2017-07-05",  150, "RUB", "5808"                 , "Яндекс.Деньги"            , "Спасибо за расширение."],
	["2017-07-28", 1000, "RUB", ""                     , "Яндекс.Деньги"            , "Лучший"],
	["2017-07-30",  125, "RUB", "Oleg Korotych"        , "WebMoney"                 , "Спасибо"],
	["2017-07-30",   10, "USD", "Jonathan Kobayashi"   , "PayPal"                   , "Thank you for implementing the chat under the video! You're the first developer that has turned my feedback into reality. Keep up the great work!"],
	["2017-10-24",  575, "RUB", ""                     , "Яндекс.Деньги"            , ""],
	["2017-11-07",   84, "RUB", "Eremite B"            , "PayPal"                   , ""],
	["2017-11-11",    1, "EUR", "Jeroen Mennen"        , "PayPal"                   , "https://www.youtube.com/watch?v=M7b80Eb0hR‍k"],
	["2017-11-12",    2, "USD", "Nathaniel Tan"        , "PayPal"                   , ""],
	["2017-12-01",    5, "CHF", "Jan Zimmermann"       , "PayPal"                   , "thanks for making this great extension. it's not a lot. hope it helps :)"],
	["2017-12-13",  500, "RUB", ""                     , "Яндекс.Деньги"            , ""],
	["2017-12-18",   10, "USD", "Fabrice Denis"        , "PayPal"                   , "Great addon. Thank you."],
	["2017-12-20",  338, "JPY", "石橋 僚太"             , "PayPal"                   , "twitch5 donate"],
	["2017-12-23",   25, "USD", "Timothy Kimball"      , "PayPal"                   , ""],
	["2018-01-08",   15, "CHF", "Urs Stettler"         , "PayPal"                   , ""],
	["2018-01-09",  500, "RUB", "Ivan Ivanov"          , "PayPal"                   , "Good job."],
	["2018-01-23",    3, "GBP", "Adam Barnett"         , "PayPal"                   , ""],
	["2018-03-04",  2.5, "USD", "shogo89"              , "WebMoney"                 , "horoshee"],
	["2018-03-06",   50, "SEK", "Magnus Hellström"     , "PayPal"                   , "Thanks for your hard work, I'm really enjoying your \"alternate player\", It's a great extension."],
	["2018-03-07",    5, "CAD", "David Ruck"           , "PayPal"                   , "Thanks for the extension. Hope to see some good things from it in the future."],
	["2018-03-07",    5, "CHF", "Urs Stettler"         , "PayPal"                   , ""],
	["2018-03-08",    3, "EUR", "Alexander Dmytriienko", "PayPal"                   , ""],
	["2018-03-13",    5, "EUR", "Justin Mages"         , "PayPal"                   , "Alternate Player for Twitch.tv is just that amazing"],
	["2018-04-04",    5, "USD", "Nyle Graham"          , "PayPal"                   , "Thanks for twitch 5"],
	["2018-04-07",   10, "USD", "William Gaebelein"    , "PayPal"                   , ""],
	["2018-04-08",   10, "EUR", "Petru Vlad Rosca"     , "PayPal"                   , "Thank you for a great Firefox extension"],
	["2018-04-08",   10, "USD", "Eric Kuehl"           , "PayPal"                   , "Thanks for the extension my dude"],
	["2018-04-24",   10, "USD", "Mohamed Husain"       , "PayPal"                   , "I can barely watch twitch without the extension anymore! Glad to see you updating so quickly to fix things twitch breaks."],
	["2018-04-25",    3, "GBP", "Simon Mound"          , "PayPal"                   , "Thanks for a great extension dude."],
	["2018-04-25",    5, "USD", "Christian Abate"      , "PayPal"                   , ""],
	["2018-04-25",    5, "USD", "Rough Image Studios"  , "PayPal"                   , "Thanks for making a great extension and keeping it regularly updated. Keep up the good work."],
	["2018-04-25",    5, "USD", "Benjamin Larkin"      , "PayPal"                   , "extension has really improved my twitch experience. thank you for taking your personal time to develop this free for us. <3"],
	["2018-04-25",    5, "EUR", "C Angelovski"         , "PayPal"                   , ""],
	["2018-04-25",   40, "RUB", "7963"                 , "Яндекс.Деньги"            , ""],
	["2018-04-25",   50, "SEK", "Patrick Skogh"        , "PayPal"                   , "Thanks for a well made addon!"],
	["2018-04-26",    3, "GBP", "Nathan Tran"          , "PayPal"                   , "Much needed QoL and visual features, thanks."],
	["2018-05-19",   10, "USD", "Alekseb"              , "WebMoney"                 , "thanks for a great extension"],
	["2018-05-28",  300, "RUB", "Fedor Stepanov"       , "PayPal"                   , "Спасибо за отличное расширение!"],
	["2018-05-29",  219, "RUB", ""                     , "WebMoney"                 , ""],
	["2018-06-11",    4, "GBP", "Todor Dobrev"         , "PayPal"                   , ""],
	["2018-06-12", 1000, "RUB", "7947"                 , "Яндекс.Деньги"            , "Большое спасибо за отличное расширение! Родной плеер твича стал показывать рекламу, несмотря на адблок, а в этом плеере и рекламы нет, и сам работает гораздо лучше. Продолжай в том же духе!"],
	["2018-06-13",    5, "GBP", "Josh Bartram"         , "PayPal"                   , "Excellent service, thankyou for providing and keeping it updated. If I can, I will donate monthly. Keep being awesome :)"],
	["2018-06-16",   20, "NZD", "Anthony Neville"      , "PayPal"                   , "For the moment ad-blockers are failing to block twitch ads, so I use this extension. It does the job."],
	["2018-06-16",  250, "RUB", "Коренев Никита"       , "PayPal"                   , ""],
	["2018-06-24",   20, "USD", "Ryan Barrera"         , "PayPal"                   , ""],
	["2018-07-08",   30, "PLN", "Artur Pniak"          , "PayPal"                   , ""],
	["2018-07-18",  100, "RUB", ""                     , "Яндекс.Деньги"            , ""],
	["2018-08-05",   10, "USD", "Steven East"          , "PayPal"                   , ""],
	["2018-08-15", 2000, "RUB", ""                     , "Яндекс.Деньги"            , ")))Ну блин, вопрос ток один, почему программеры твича так не могут. Тупо лучший, снова пробудил веру в человечество и светлое будущее"],
	["2018-08-21",  200, "RUB", ""                     , "Яндекс.Деньги"            , ""],
	["2018-08-21",    5, "GBP", "Todor Dobrev"         , "PayPal"                   , ""],
];
